---
# tasks file for pbis
  - include: redhat.yml
    when: ansible_os_family == 'RedHat'

  - include: ubuntu.yml
    when: ansible_os_family == 'Debian'

  - name: Check the Domain status
    shell: /opt/pbis/bin/lsa get-status |grep Netbios |awk '{print $3}'
    register: domain_status

  - name: Join the machine if it is not already on the domain.
    command: /usr/bin/domainjoin-cli join {{ domain_fqdn }} {{ domain_user }} {{ domain_pass }}
    when: domain_status.stdout != "{{ domain_netbios }}"
  
  - name: config pbis requiremembershipof
    command: /opt/pbis/bin/config RequireMembershipOf {{ require_membership_of }}

  - name: config pbis domain
    command: /opt/pbis/bin/config AssumeDefaultDomain {{ assume_default_domain }}

  - name: config pbis shell
    command: /opt/pbis/bin/config LoginShellTemplate {{ login_shell_template }}

  - name: config pbis homedirtemplate
    command: /opt/pbis/bin/config HomeDirTemplate {{ homedir_template }}

  - name: config pbis userdomainprefix
    command: /opt/pbis/bin/config UserDomainPrefix {{ domain_netbios }}